version: "3"

services:
  planner_api:
    build: ./python
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    env_file:
      - .env
    volumes:
      - "../../:/home/python"
    ports:
      - 8000:8000
